# Generated by Django 4.2.4 on 2023-08-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('user', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=40)),
                ('rdp', models.BooleanField(default=True)),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('location', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('dns', models.CharField(max_length=40)),
                ('ip', models.CharField(max_length=15)),
                ('manufacter', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
            ],
        ),
    ]
