# Generated by Django 4.2.4 on 2023-08-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='cabinet',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
